#./django-docker/docker-compose.yml
version: '3.7'

services:
  web:
    build:
         context: ./
         dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000

    # for the specific host path or named volume to docker contains the media files and other files needed for run the app
    # volumes:
    #   - ./app/:/opt/app/
    ports:
      - 8000:8000

    # environment:
    # env_file:
    #   - ./env/django.env